### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by marshallswain**
This is building on the other PR I just made: https://github.com/tipeio/uploadcare-vue/pull/2

Update to latest vue build tools.

This upgrades to the latest `vue-template-compiler` and `vue-loader`, and updates the `webpack.config.js` to the API that works with the latest vue-loader.

I also installed `vue` as a devDependency because without it I get a "`vue-template-compiler` and `vue` version mismatch" error.

Unfortunately, this allows the build to run, but using the built files results in an error:
screen shot 2018-05-14 at 5 58 49 pm

Hopefully this will get you on your way to getting this to work.  I'm actually unable to get the `dist` version to work in the currently-published version (my webpack build with `@vue/cli v3` reports that I need to `npm i uploadcare-js` instead of the `uploadcare` package from npm), so I'm using the `src` version, directly.

### CODE REVIEW

**Comment by gdi2290** [comment]
can you rebase this? and WIP is in the title so I won't merge it until that is changed
👍 thanks for the PRs

**Comment by marshallswain** [comment]
@gdi2290 Done. 

I also updated the externals value to something that allows this to work out of the box, for me.  I no longer have to do

```js
import UploadCare from 'uploadcare-vue/src/Uploadcare.vue'
```

But can now import as expected

```js
import UploadCare from 'uploadcare-vue'
```

However, I'm not certain what impact this would have on any existing installations.

**Comment by marshallswain** [comment]
@gdi2290 would you please make a note here when you finish the npm release?  Thank you for the merges!

**Comment by gdi2290** [comment]
@marshallswain published as 1.0.0

**Pull request merged**
