### PR TITLE
ImageShrink is not a boolean anymore

### PR DESCRIPTION
**Pull request by sloba88**
ImageShrink is not a boolean but a string, it fails if you pass a boolean value

### CODE REVIEW

**Comment by realmike33** [comment]
@sloba88 will merge this if you change your [commit message](https://github.com/tipeio/tipe-conventions/blob/4987a13f29bc7e5fcbb428dd7b245fedcd5bf6ce/COMMIT_CONVENTION.md#git-commit-message-convention)

**Comment by sloba88** [comment]
> @sloba88 will merge this if you change your [commit message](https://github.com/tipeio/tipe-conventions/blob/4987a13f29bc7e5fcbb428dd7b245fedcd5bf6ce/COMMIT_CONVENTION.md#git-commit-message-convention)

I can't open the link, did you link to the private repo maybe?

**Comment by realmike33** [comment]
@sloba88 whoops! its public now

**Comment by gathrlabs** [comment]
Would be great to get this merged as this is still an outstanding issue.

**Pull request merged**
